######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 15 08:17:31 2011
######################################################################

TEMPLATE = app
TARGET = bldrtest
DEPENDPATH += .
INCLUDEPATH += .
MAKEFILE = Makefile.bldrtest

SOURCES +=            bldrtest.C 
