#!/bin/sh

# QPlot - Publication quality 2D graphs with dual coordinate systems
# Copyright (C) 2014  Daniel Wagenaar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

IFN=$1
DIR=`dirname $IFN`
LEAF=`basename $IFN`

PIDFILE=$DIR/.qp-$LEAF.pid
if [ -f $PIDFILE ]; then
  RUNNING=1
  PID=`cat $PIDFILE`
  grep -q $LEAF /proc/$PID/cmdline 2>/dev/null || RUNNING=0
else
  RUNNING=0
fi

if [ $RUNNING = "1" ]; then
  kill $PID
  unlink $PIDFILE
else
  echo qpclose: not running
fi
