#!/bin/sh

cd `dirname $0`
cd ..

echo "# Automatically generated by updatesources.sh" > src/CMakeLists.txt
echo "" >> src/CMakeLists.txt

echo "target_include_directories(qplot PUBLIC src)" >> src/CMakeLists.txt

find src -name \*.h -exec echo "target_sources(qplot PRIVATE" 'backend/{}' ")" ';' | sort -df >> src/CMakeLists.txt
find src -name \*.cpp -exec echo "target_sources(qplot PRIVATE" 'backend/{}' ")" ';' | sort -df >> src/CMakeLists.txt

