#                                                          -*- Makefile -*-
# DO NOT RUN THIS MAKEFILE IN PLACE. Use toplevel Makefile instead.

ALL: qplot-directuse.pdf HTML

HTML: REF TUT CSS HOME PYREF PYTUT

OCTAVE=../tools/octavex

# Octave Reference material
REFEGMS=$(subst ../doc/ref,html/ref,$(wildcard ../doc/ref/*_eg.m))
REFEGPDFS=$(patsubst %_eg.m,%.pdf,$(REFEGMS))
REFEGPNGS=$(patsubst %_eg.m,%.png,$(REFEGMS))
REFEGHTMLS=$(patsubst %_eg.m,%.html,$(REFEGMS))

REF: $(REFEGMS) $(REFEGPDFS) $(REFEGPNGS) $(REFEGHTMLS) \
	html/ref/alpha.html html/ref/catg.html

html/ref/alpha.html: ../tools/mkalpha.pl
	$< ../octave/qplot-0.2 $@

html/ref/catg.html: ../tools/mkcatg.pl ../doc/matlab-org.txt
	$< ../doc/matlab-org.txt $@

html/ref/%_eg.m: ../doc/ref/%_eg.m
	mkdir -p html/ref
	cp $^ $@

html/ref/%.pdf: html/ref/%_eg.m ../tools/runmeg.m
	( cd html/ref; ../../../tools/octavee "runmeg('$<')" )
html/ref/%.png: html/ref/%_eg.m ../tools/runmeg.m
	( cd html/ref; ../../../tools/octavee "runmeg('$<')" )

#$(REFEGPDFS) $(REFEGPNGS): $(REFEGMS) ../tools/alleg.m
#	(cd html/ref; ../../$(OCTAVE) ../../../tools/alleg.m ) && touch $@

$(REFEGHTMLS): ../tools/m2html.pl $(REFEGMS) $(REFEGPNGS)
	$<

# Python Reference material
PYREFEGMS=$(subst ../doc/pyref,html/pyref,$(wildcard ../doc/pyref/*_eg.py))
PYREFEGPDFS=$(patsubst %_eg.py,%.pdf,$(PYREFEGMS))
PYREFEGPNGS=$(patsubst %_eg.py,%.png,$(PYREFEGMS))
PYREFEGHTMLS=$(patsubst %_eg.py,%.html,$(PYREFEGMS))

PYREF: $(PYREFEGHTMLS) $(PYREFEGPDFS) $(PYREFEGPNGS) $(PYREFEGMS) \
	html/pyref/alpha.html html/pyref/catg.html \
	PYREFCHECK

$(PYREFEGHTMLS): html/pyref/%.html: html/pyref/%.pdf html/pyref/%.png

PYREFCHECK: ../tools/checkpyeg.py $(PYREFEGHTMLS) 
	../tools/checkpyeg.py

html/pyref/alpha.html: ../tools/mkpyalpha.py
	$< ../python/qplot $@

html/pyref/catg.html: ../tools/mkpycatg.py ../doc/python-org.txt
	$< ../doc/python-org.txt $@

html/pyref/%_eg.py: ../doc/pyref/%_eg.py
	mkdir -p html/pyref
	cp $^ $@

html/pyref/%.pdf: html/pyref/%_eg.py ../tools/runpyeg.py
	../tools/runpyeg.py $< $@

html/pyref/%.png: html/pyref/%_eg.py ../tools/runpyeg.py
	../tools/runpyeg.py $< $@

html/pyref/%.html: html/pyref/%_eg.py html/pyref/%.png ../tools/py2html.py 
	../tools/py2html.py $@

# Octave Tutorial material
TUTHTMLS=$(subst ../doc/tut,html/tut,$(wildcard ../doc/tut/tut-*.html))
TUTMS=$(subst ../doc/tut,html/tut,$(wildcard ../doc/tut/tut-*.m))
TUTPNGS=$(subst tut,html/tut/tut,tut-01-01.png tut-02-01.png tut-02-02.png tut-02-03.png tut-03-01.png tut-03-02.png tut-03-03.png)

TUT: $(TUTHTMLS) $(TUTMS) $(TUTPNGS)

html/tut/%.html: ../doc/tut/%.html
	mkdir -p html/tut
	cp $^ $@

html/tut/%.m: ../doc/tut/%.m
	mkdir -p html/tut
	cp $^ $@

html/tut/tut-01-01.png: ../doc/tut/tut-01-01.png
	mkdir -p html/tut
	cp $^ $@

html/tut/tut-02-01.png html/tut/tut-02-02.png html/tut/tut-02-03.png: html/tut/tut-01.m
	(cd html/tut; ../../$(OCTAVE) ../../$< )

html/tut/tut-03-01.png html/tut/tut-03-02.png html/tut/tut-03-03.png: html/tut/tut-03.m
	(cd html/tut; ../../$(OCTAVE) ../../$< )

# Python Tutorial material
PYTUTHTMLS=$(subst ../doc/pytut,html/pytut,$(wildcard ../doc/pytut/pytut-*.html))
PYTUTMS=$(subst ../doc/pytut,html/pytut,$(wildcard ../doc/pytut/pytut-*.py))
PYTUTPNGS=$(subst pytut,html/pytut/pytut,pytut-01-01.png pytut-02-01.png pytut-02-02.png pytut-02-03.png pytut-03-01.png pytut-03-02.png pytut-03-03.png)

PYTUT: $(PYTUTHTMLS) $(PYTUTMS) $(PYTUTPNGS)

html/pytut/%.html: ../doc/pytut/%.html
	mkdir -p html/pytut
	cp $^ $@

html/pytut/%.py: ../doc/pytut/%.py
	mkdir -p html/pytut
	cp $^ $@

html/pytut/pytut-01-01.png: ../doc/pytut/pytut-01-01.png
	mkdir -p html/pytut
	cp $^ $@

html/pytut/pytut-02-01.png html/pytut/pytut-02-02.png html/pytut/pytut-02-03.png: html/pytut/pytut-01.py
	(cd html/pytut; python3 ../../$< )

html/pytut/pytut-03-01.png html/pytut/pytut-03-02.png html/pytut/pytut-03-03.png: html/pytut/pytut-03.py
	(cd html/pytut; python3 ../../$< )

# Style files
CSSS=$(subst ../doc/css,html/css,$(wildcard ../doc/css/*.css))

CSS: $(CSSS)

html/css/%.css: ../doc/css/%.css
	mkdir -p html/css
	cp $^ $@

# HOME folder
HOMEMS=$(subst ../doc/home,html/home,$(wildcard ../doc/home/eg_*.m))
HOMEPDFS=$(patsubst %.m,%.pdf,$(HOMEMS))
HOMEPNGS=$(patsubst %.m,%.png,$(HOMEMS))
HOMEHTML=$(subst ../doc/home,html,$(wildcard ../doc/home/*.html))

HOME: $(HOMEPNGS) $(HOMEPDFS) $(HOMEHTML) $(HOMEMS)

html/home/%.m: ../doc/home/%.m
	mkdir -p html/home
	cp $^ $@

html/%.html: ../doc/home/%.html
	mkdir -p html
	cp $^ $@

html/home/eg_ephys.png: ../doc/home/eg_ephys.png
	mkdir -p html/home
	cp $^ $@

html/home/eg_ephys.pdf: ../doc/home/eg_ephys.pdf
	mkdir -p html/home
	cp $^ $@

html/home/%.png html/home/%.pdf: html/home/%.m
	( cd html/home; ../../$(OCTAVE) ../../$^ )


# Direct use
qplot-directuse.pdf: ../doc/qplot-directuse.tex directuse-eg.pdf
	pdflatex $<

directuse-eg.pdf: ../doc/directuse-eg.qpt
	DISPLAY=`../tools/ensurexvfb` ../build/qplot $< $@

cleanup:
	rm -f *.aux *.dvi *.log
	rm -f html/*/*.qpt
	rm -f html/*/.*.pid

clean: cleanup
	rm -rf html

.PHONY: clean cleanup HOME ALL HTML
