#!/usr/bin/perl -w

use strict;

# QPlot - Publication quality 2D graphs with dual coordinate systems
# Copyright (C) 2014  Daniel Wagenaar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This drops Matlab's private labraries from the library path.
# This version optimized for running in sshfs-mounted location.

use Cwd;

my @args = @ARGV;

my $libpath = $ENV{LD_LIBRARY_PATH} || "";
my @libs = split(/:/, $libpath);
my @olibs;
for (@libs) {
  push @olibs, $_ unless $_ =~ /matlab/;
}
$ENV{LD_LIBRARY_PATH} = join(":", @olibs);

my $cwd = Cwd::cwd();

for (@args) {
  if (/\./ && !(/^\//)) {
    $_ = "$cwd/$_";
  }
}

chdir('/tmp');

my $qplotbin = $ENV{QPLOT_BINARY} || "qplot";
unshift @args, $qplotbin;

exec(@args);
