#!/bin/sh

# (C) Daniel Wagenaar, 2008

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.

# This program is inspired by xvfb-run.sh:
# Copyright (C) 2005 The T2 SDE Project
# Copyright (C) XXXX - 2005 Debian

HERE=`dirname $0`
MNAME=$1

export DISPLAY=`$HERE/ensurexvfb`

PATH=$HERE/../build:$PATH /usr/bin/octave --no-gui --path $HERE/../octave/qplot-0.2 $MNAME
