######################################################################
# Automatically generated by qmake (1.07a) Tue Jun 14 15:35:31 2011
######################################################################

TEMPLATE = app
INCLUDEPATH += .
MOC_DIR = .moc
OBJECTS_DIR = .obj

# Input
HEADERS += Axis.H Command.H Figure.H Token.H Statement.H
SOURCES += Axis.C Command.C Figure.C Token.C Statement.C
HEADERS += CmdPlot.H
SOURCES += CmdPlot.C
	
SOURCES += Test.C
MAKEFILE = Makefile.test
