#!/usr/bin/python3

import os
import glob

if not os.path.exists("build"):
    os.mkdir("build")
os.chdir("build")
if not os.path.exists("octref"):
    os.mkdir("octref")
os.chdir("octref")

egpath = "../../source/octave-egs"
egs = glob.glob(f"{egpath}/q*_eg.m")
qplotpath = "../../../octave/qplot"
codepath = "../../code"

def needrebuild(eg):
    leaf = eg.split("/")[-1]
    func = leaf[:-5]
    pdffn = f"./{func}.pdf"
    pngfn = f"./{func}.png"
    if not os.path.exists(pngfn) or not os.path.exists(pdffn):
        return True
    stm = os.stat(eg)
    stpng = os.stat(pngfn)
    stpdf = os.stat(pdffn)
    return stpng.st_size==0 or stpdf.st_size==0 \
           or stm.st_mtime > stpng.st_mtime \
           or stm.st_mtime > stpdf.st_mtime

def buildall(egs):
    for eg in egs:
        if not needrebuild(eg):
            continue
        os.system(f"cp -a {eg} .")
        os.system(f"""/usr/bin/octave --no-gui --path {egpath} --path {qplotpath} --path {codepath} --eval "octeg('{eg}')" """)



def hidedisplay():
    with os.popen("ensurexvfb") as f:
        txt = f.read()
        os.environ["DISPLAY"] = txt.strip()


hidedisplay()        
buildall(egs)        
