#!/usr/bin/python3

# QPlot - Publication quality 2D graphs with dual coordinate systems
# Copyright (C) 2014-2023  Daniel Wagenaar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import re
import subprocess

sys.path.append("../python")
import qplot as qp

sys.path.append("./code")
import qppydoclib as qpd
import qphtmllib as qph


examples = [("Electrophysiology", "eg_ephys"),
            ("Image data", "eg_imsc"),
            ("Bar graph", "eg_bars"),
            ("Polar plot", "eg_circ"),
            ("Data and guides", "eg_gline")
            ]



def readhtml(ifn):
    with open(ifn, "r") as fd:
        body = fd.read()
    return body


def document(body, base):
    eg_dct = {fn: ttl for ttl, fn in examples}
    eg_sibs = [(ttl, f"{fn}.html") for ttl, fn in examples]
    crumbs = [("Getting started", "index.html")]
    if base.startswith("eg_"):
        title = "Example: " + eg_dct[base]
        crumbs.append((eg_dct[base], None))
        sibs = [eg_sibs]
    else:
        title = crumbs[0][0]
        sibs = [eg_sibs]
    html = qph.doctype()
    html += "<html>"
    html += qph.head(title, 1)
    html += """<body class="language-python">"""
#    html += f"""<script src="../css/prism.js"></script>"""
    html += '<div class="contents">'
    html += qph.sidebar(crumbs, sibs, dirlevel=1)
    html += '<div id="central">'
    html += qph.header()
    html += qph.idxtitleblock(title)
    html += '<div class="rst">'
    html += body
    html += '</div>\n' # rst
    html += qph.footer()
    html += '</div>\n' # central
    html += '<div id="rightspace"></div>'
    html += '</div>\n' # contents
    return html


def main():
    ifn = sys.argv[1]
    ofn = sys.argv[2]
    base = ifn.split("/")[-1].split(".")[0]
    body = readhtml(ifn)
    html = document(body, base)
    with open(ofn, "w") as fd:
        fd.write(html)

        
main()

    
