name: 'Install NSIS'
description: 'Installs NSIS including the EnvVar plugin (only supported on Windows)'
author: 'repolevedavaj'
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  nsis-version:
    required: true
    description: 'The version of NSIS to install'
runs:
  using: "composite"
  steps:
    - name: Install NSIS
      run: |
        Invoke-WebRequest https://prdownloads.sourceforge.net/nsis/nsis-${{ inputs.nsis-version }}-setup.exe -OutFile C:\WINDOWS\Temp\nsis-${{ inputs.nsis-version }}-setup.exe
        $process = Start-Process "C:\WINDOWS\Temp\nsis-${{ inputs.nsis-version }}-setup.exe" -ArgumentList "/S" -Wait -PassThru
        $exitCode = $process.ExitCode
          if ($exitCode -eq 0) {
              Write-Host "Installer ran successfully."
          } else {
              Write-Host "Installer failed with exit code $exitCode."
              exit $exitCode
          }
        echo "C:\Program Files (x86)\NSIS\Bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
        echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath "$env:GITHUB_PATH" -Append
      shell: pwsh

# Adapted from https://github.com/repolevedavaj/install-nsis
# The MIT license applies: https://github.com/repolevedavaj/install-nsis/blob/main/LICENSE