on: 
  push:
    branches: [ "main" ]
    tags: ["v*"]
    workflow_dispatch:

name: Build backend on Windows


jobs:
  build:
    name: Build binary
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install NSIS
        run: |
          Invoke-WebRequest https://prdownloads.sourceforge.net/nsis/nsis-3.11-setup.exe -OutFile C:\WINDOWS\Temp\nsis-setup.exe
          $process = Start-Process "C:\WINDOWS\Temp\nsis-setup.exe" -ArgumentList "/S" -Wait -PassThru
          $exitCode = $process.ExitCode
            if ($exitCode -eq 0) {
                Write-Host "Installer ran successfully."
            } else {
                Write-Host "Installer failed with exit code $exitCode."
                exit $exitCode
            }
          echo "C:\Program Files (x86)\NSIS\Bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath "$env:GITHUB_PATH" -Append
        shell: pwsh
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
      - name: Prepare build directory
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build binary
        run: cmake --build build --config=Release
      - name: Create installer
        working-directory: ./build
        run: cpack
      - name: Upload .exe
        uses: softprops/action-gh-release@v2
        with:
          name: winexe
          files: build/QPlot*exe
          token: ${{github.TOKEN}}
          retention-days: 3

  release:
    name: Create release and publish to Github
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: winexe
          path: build/
      - name: Upload .exe
        uses: softprops/action-gh-release@v2
        with:
          files: build/QPlot*exe
          token: ${{github.TOKEN}}
                  
    
# The NSIS installer was adapted from https://github.com/repolevedavaj/install-nsis
# The MIT license applies: https://github.com/repolevedavaj/install-nsis/blob/main/LICENSE